# 아직 구분안되어 있음
server:
  port: 8080  # ? ?? ?? ??
  servlet:
    context-path: /api # 공통 경로 설정

spring:
  datasource:
    url: jdbc:postgresql://54.180.80.2:5432/trip_memo  # PostgreSQL ?????? URL
    username: postgres  # ?????? ??? ??
    password: postgres  # ?????? ????
    driver-class-name: org.postgresql.Driver  # JDBC ???? ??? ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: user
      password: 2758

  jpa:
    hibernate:
      ddl-auto: update  # JPA ??? ?? ?? ??
    show-sql: true  # SQL ?? ?? ??
    properties:
      hibernate:
        format_sql: true  # SQL ?? ??? ??

logging:
  level:
    org:
      hibernate:
        type: trace  # Hibernate ?? ??

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 86400 # ttl (초)