server:
  port: 8080  # ? ?? ?? ??
  servlet:
    context-path: /api # 공통 경로 설정


spring:
  datasource:
#    url: jdbc:postgresql://54.180.80.2:5432/trip_memo  # PostgreSQL ?????? URL
    url: jdbc:postgresql://54.180.80.2:5432/trip_memo  # PostgreSQL ?????? URL
    username: postgres  # ?????? ??? ??
    password: 1234  # ?????? ????
    driver-class-name: org.postgresql.Driver  # JDBC ???? ??? ??
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: user
      password: 2758

  jpa:
    hibernate:
      ddl-auto: update  # JPA ??? ?? ?? ??
    show-sql: true  # SQL ?? ?? ??
    properties:
      hibernate:
        format_sql: true  # SQL ?? ??? ??

logging:
  level:
    org:
      hibernate:
        type: trace  # Hibernate ?? ??

