name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t trip-memo .

    - name: Push to Docker Registry
      run: |
        docker tag trip-memo:latest ${{ secrets.DOCKER_USERNAME }}/trip-memo:latest
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/trip-memo:latest

    - name: Deploy to AWS EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.180.80.2 "docker pull ${{ secrets.DOCKER_USERNAME }}/trip-memo:latest && docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/trip-memo:latest"
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
